### ISSUE TITLE
Ability to specify Github api endpoint

### ISSUE THREAD

**Issue by jhaals** [nhmood/watson-ruby#115]
Allowing users to specify API endpoint in rc would support Github Enterprise since the API is the same.

**Comment by nhmood** [comment]
@JHaals do you happen to have access to GitHub Enterprise?

I have implemented (what I think should be) support for the API endpoint in https://github.com/nhmood/watson-ruby/tree/github_enterprise
I have tested to make sure that it works with the regular https://api.github.com and since you mentioned the API is the same I am guessing it will work with other endpoints. Could you test this out and let me know if it works so I can merge it into master?

**Comment by jhaals** [comment]
@nhmood got it.

It works fine :+1: 
However it might be good to strip the trailing / from the user input

https://enterprise/api/v3/

```
[ x ] Unable to obtain OAuth Token
      Status: 404 - Not Found
```

https://enterprise/api/v3 - works fine

**Comment by jhaals** [comment]
#201 should sort that issue

**Comment by nhmood** [comment]
Pulled into master, thanks for suggesting this :)

**Comment by jhaals** [comment]
Thank you
