### ISSUE TITLE
option to not show [o] files?

### ISSUE THREAD

**Issue by cj** [nhmood/watson-ruby#121]
Hi,

This gem seems impossible to use with rails as there are tons of files, so it just gets flooded with `[o]`, is there a way to just show files with tags in them?

**Comment by nhmood** [comment]
This is definitely something I need to add, I'm not sure why I didn't think of this earlier! 
I'll put this on the more immediate todo list (few bug fixes beforehand, but this should be a quick fix)

**Comment by nhmood** [comment]
Fixed with 7da363704d6900438135b3591a353254d6f30222, available in the latest gem also (v1.1.0)

Now supports `-s / --show [ALL, CLEAN, DIRTY]` where clean returns only files without issues in them, dirty returns only files with issues in them, and all returns both.

The default behavior of watson is `all`. If you think it would be useful to have the default behavior be a option in the .watsonrc config file open a new issue and I can add that there. Until then, you can always just `alias watson="watson -s dirty"`

**Comment by cj** [comment]
@nhmood thank you so much for adding this!
