### ISSUE TITLE
watson doesn't use $HOME/.watsonrc's [tags] entries

### ISSUE THREAD

**Issue by cbowns** [nhmood/watson-ruby#208]
I added a couple of tags to my `.watsonrc` file in `$HOME`, but watson didn't pick those additions up in a new project using watson for the first time, nor in an existing project (i.e. created before I added the tags to `~/.watsonrc`.)

I was expecting watson to either base the project's .rc file off my main .watsonrc, or to combine the two when evaluating the tags list.

(I'll look at adding support for one of these behaviours.)

**Comment by nhmood** [comment]
As of right now watson creates a unique `.watsonrc` in every directory that it is run in. 
The reason behind this was that you might want to have different settings on a per project basis (tags, ignores, dirs, and especially unique GitHub / Bitbucket login/repo information).
So as of right now, the behavior you described is not supported.

However, you bring up a good idea that it would be nice for watson to merge a default `~/.watsonrc` with the config in the users current working directory. I'm not a fan of combining the two (`$HOME` and current directory) only because it might lead to some confusion as to what is being referenced. But using the `$HOME` config as a reference for all newly created configs is a great idea, I'll take a look at implementing it unless you already have a solution or would like to work on it.

**Comment by cbowns** [comment]
Thanks for explaining what your thinking was behind it. I know `git` does some trickery to have a hierarchy of `.rc` files but that seems like overkill. I think a simple fork at creation time seems pretty reasonable.

**Comment by cbowns** [comment]
Looks great in 1.6.1, thanks!
