### ISSUE TITLE
Unique identifiers for issues in watson

### ISSUE THREAD

**Issue by profan** [nhmood/watson-ruby#232]
When you add an issue in the code, watson should upon parsing the issue in the code add a string of text to the end representing the unique identifier for that specific issue.

So that when you move an issue in the code, IE two lines up in the same file, watson would find that the issue already exists on GitHub/Bitbucket/Gitlab thanks to the unique identifier and just updates the existing one, right now it would create another issue even if it already exists.

**Comment by nhmood** [comment]
If you look at https://github.com/nhmood/watson-ruby/blob/master/lib/watson/parser.rb#L325
you will see that the MD5 generated is using the `tag`, `relative_path`, and `title` in order to create the MD5 that is put into the body of the posted issue.

Those shouldn't change unless the author explicitly is changing the issue itself (relative path is used so moving the directory won't affect it, but if `watson` is run from a different location it **will** change the relative path)

Are you seeing reposting behavior and if so could you give some details about when/how you are seeing it?

**Comment by profan** [comment]
Ah, that makes sense.

I'll test doing the same thing again and report back with what happens and the steps to reproduce it, if it does happen again that is (could have been an oversight on my behalf).

Seems like it was just an oversight on my behalf, must have run it from another directory the first time.
